force-app/main/default/objects/Account/fields/Document_number__c.field-meta.xml
<CustomField>
    <fullName>Document_number__c</fullName>
    <label>Document number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identification_type__c.field-meta.xml
<CustomField>
    <fullName>Identification_type__c</fullName>
    <label>Identification type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>TI</fullName>
            </value>
            <value>
                <fullName>PP</fullName>
            </value>
            <value>
                <fullName>NIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
private with sharing class AccountTriggerTest {
    @TestSetup
    static void makeData(){
        Account anAccount = new Account(
            Name = 'Globant',
            Document_number__c = '33333333',
            Identification_type__c = 'NIT'
        );
        insert anAccount;
    }

    @IsTest
    static void methodName(){
        Account anAccount = new Account(
            Name = 'Globant',
            Document_number__c = '33333333',
            Identification_type__c = 'NIT'
        );
        Test.startTest();
        Database.SaveResult result = Database.insert(anAccount, false);
        Test.stopTest();

        System.assertEquals(false, result.isSuccess(), 'se inserto la cuenta');
        System.assertEquals(
            'No se puede insertar una cuenta con document number e identification type iguales', 
            result.getErrors()[0].getMessage(), 
            'el mensaje de error no coincide'
        );
    }
}